version: "3.9"

services:

  orchestration:
    build:
      context: ./orchestration_service
    container_name: orchestration_service
    ports:
      - "8000:8000"
    volumes:
    - ./orchestration_service:/app 
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  scraper:
    build:
      context: ./scraper_service
    container_name: scraper_service
    ports:
      - "8001:8000"
    volumes:
    - ./scraper_service:/app 
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  insights:
    build:
      context: ./insights_service
    container_name: insights_service
    ports:
      - "8002:8000"
    volumes:
    - ./insights_service:/app 
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: